<?php
// routes.php — URL pattern => "Controller@action"
// {id}   matches a number, {slug} matches a URL-friendly word.

return [
    "GET" => [
        "/"                 => "HomeController@index",
        "/products"         => "ProductController@index",
        "/product/{slug}"   => "ProductController@show",
        "/search"           => "ProductController@search",
        "/cart"             => "CartController@index",
        "/checkout"         => "CheckoutController@index",
        "/order/{id}"       => "CheckoutController@order",
        "/register"         => "AuthController@registerForm",
        "/login"            => "AuthController@loginForm",
        "/account"          => "AccountController@profile",
        "/account/orders"   => "AccountController@orders",
        "/account/orders/{id}" => "AccountController@orderDetail",
        "/returns"          => "ReturnsController@landing",
        "/returns/start"    => "ReturnsController@start",
        "/returns/{id}"     => "ReturnsController@show",
        "/deliver-to"       => "DeliverController@index",
        "/admin"            => "AdminController@dashboard",
        "/admin/products"   => "AdminController@products",
        "/admin/products/new" => "AdminController@newProduct",
        "/admin/products/{id}/edit" => "AdminController@editProduct",
        "/admin/categories" => "AdminController@categories",
        "/admin/orders"     => "AdminController@orders",
        "/admin/orders/{id}" => "AdminController@orderDetail",
        "/admin/returns"    => "AdminController@returns",
        "/admin/returns/{id}" => "AdminController@returnDetail",
        "/admin/users"      => "AdminController@users",
        "/admin/reviews"    => "AdminController@reviews",
        "/deals"            => "DealsController@index",
        "/gift-cards"       => "GiftCardsController@index",
        "/customer-service" => "StaticController@customerService",
        "/registry"         => "StaticController@registry",
        "/sell"             => "StaticController@sell",
        "/about"            => "StaticController@about",
        "/careers"          => "StaticController@careers",
        "/sustainability"   => "StaticController@sustainability",
        "/affiliate"        => "StaticController@affiliate",
        "/advertise"        => "StaticController@advertise",
        "/shipping-policies" => "StaticController@shippingPolicies",
        "/help"             => "StaticController@help",
    ],

    "POST" => [
        "/cart/add"         => "CartController@add",
        "/cart/update"      => "CartController@update",
        "/cart/remove"      => "CartController@remove",
        "/reviews"          => "ReviewController@store",
        "/reviews/delete"   => "ReviewController@destroy",
        "/checkout"         => "CheckoutController@create",
        "/checkout/complete" => "CheckoutController@complete",
        "/register"         => "AuthController@register",
        "/login"            => "AuthController@login",
        "/logout"           => "AuthController@logout",
        "/returns/submit"   => "ReturnsController@submit",
        "/admin/products"   => "AdminController@createProduct",
        "/admin/products/{id}" => "AdminController@updateProduct",
        "/admin/products/{id}/delete" => "AdminController@deleteProduct",
        "/admin/categories" => "AdminController@createCategory",
        "/admin/categories/{id}/delete" => "AdminController@deleteCategory",
        "/admin/orders/{id}/status" => "AdminController@updateOrderStatus",
        "/admin/orders/{id}/cancel" => "AdminController@cancelOrder",
        "/admin/returns/{id}/status" => "AdminController@updateReturnStatus",
        "/admin/users/{id}/toggle-admin" => "AdminController@toggleAdmin",
        "/admin/reviews/{id}/delete" => "AdminController@deleteReview",
        "/admin/products/{id}/duplicate" => "AdminController@duplicateProduct",
    ],
];
